default:
    tags:
        - pronto

stages:
    - Build
    - Unit Tests
    - Coverage

Dependencies:
    stage: Build
    script:
        - python3 -m pip install -r requirements.txt

APIQuery:
    stage: Unit Tests
    variables:
        TARGET: .coverage_APIQuery
    script:
        - python3 -m pytest -v --cov --cov-config=.cov_conf ./pytests/test_APIQuery.py
    artifacts:
        paths:
          - .coverage_APIQuery

Boundary Detector:
    stage: Unit Tests
    variables:
        TARGET: .coverage_BoundaryDetector
    script:
        - python3 -m pytest -v --cov --cov-config=.cov_conf ./pytests/test_BoundaryDetector.py
    artifacts:
        paths:
          - .coverage_BoundaryDetector

Model:
    stage: Unit Tests
    variables:
        TARGET: .coverage_Model
    script:
        - python3 -m pytest -v --cov --cov-config=.cov_conf ./pytests/test_Model.py
    artifacts:
        paths:
          - .coverage_Model

Coverage Report:
    stage: Coverage
    script:
        - python3 -m coverage combine .coverage_*
        - python3 -m coverage html
        - python3 -m coverage xml
        - python3 -m coverage report
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        reports:
            cobertura: coverage.xml
        name: Coverage HTML
        paths:
            - htmlcov/

        